name: Code Quality Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: mbstring, xml, ctype, iconv, intl, bcmath, pdo_sqlite
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Cache PHPStan & Rector
        uses: actions/cache@v4
        with:
          path: |
            tmp/phpstan
            tmp/rector
          key: ${{ runner.os }}-qa-caches-${{ hashFiles('**/composer.lock', '**/phpstan.neon*', '**/rector.php') }}
          restore-keys: |
            ${{ runner.os }}-qa-caches-

      - name: Execute Laravel Pint
        run: composer pint-ci

      - name: Execute Rector
        run: composer rector-dry

      - name: Execute PHPStan
        run: composer phpstan
